### ISSUE TITLE
Missing Example Module in New CraftCMS Projects Created via Composer

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/craft#105]
### Description
According to the [CraftCMS documentation](https://craftcms.com/docs/5.x/reference/config/app.html#content), new project bootstrap an example module. However, when creating a new project using composer create-project, the generated code does not contain the example module mentioned in the docs.

### Steps to reproduce

1. Run `composer create-project craftcms/craft` to set up a new CraftCMS project.
2. Check the `app.php` or `/modules/` for the missing module in app.php.

**Comment by AugustMiller** [comment]
Ah, whoops! Yeah, we made the decision to remove the module in favor of bundling [`craftcms/generator`](https://github.com/craftcms/generator), which is capable of initializing an equivalent Module class. Run this command to get started:

```bash
ddev craft make module
```

I just pushed a couple of updates to the config + extension docs to clarify this.
