### ISSUE TITLE
Defaults for command line install

### ISSUE THREAD

**Issue by wbrowar** [craftcms/craft#12]
Hey folks, I don't know if this belongs here or in the `cms` repo, but here's an FR for the command line installer:

Could it be possible to create defaults for Site Name and Site URL based on the existence of those settings in the `.env` file? Just like the Database seems to pull from the DB settings in `.env`, it would be great to be able to bypass those by having `{siteName}` and `{siteUrl}` populated by default.

Even better, for the sake of easier automation, it would be great to be able to run `./craft setup` with all of the questions answered through command line arguments. For example, you could run `./craft setup --site_url="{siteUrl}"  --site_name="{siteName}" etc...` to bypass all of the questions altogether.

**Comment by brandonkelly** [comment]
Hey @wbrowar can you repost this at the craftcms/cms repo please?

**Comment by wbrowar** [comment]
All set! Thanks for taking a look.

Will
