### ISSUE TITLE
Consider renaming craftcms/craft

### ISSUE THREAD

**Issue by ostark** [craftcms/craft#15]
After working with Craft 3 for a while and contributing to `craftcms/cms` a bit recently, I know the difference between `craftcms/craft` and `craftcms/cms`. 

However, for newcomers to Craft 3 and to composer in general, the very similar package naming can be confusing. If the name of the package would reflect the purpose it would help. Here are my suggestions:

* craftcms/skeleton
* craftcms/project
* craftcms/starter

**Comment by brandonkelly** [comment]
For some context, here’s what some other projects are doing:

Laravel
- source: laravel/framework
- project: laravel/laravel

Drupal
- source: drupal/core
- project: drupal/drupal

Yii
- source: yiisoft/yii2
- project: yiisoft/yii2-app-basic / yiisoft/yii2-app-advanced

Symfony
- source: symfony/symfony
- project: symfony/framework-standard-edition

So not too much in the way of conventions, but Laravel and Drupal both do the same thing we do - where they've used the app name (`laravel` / `drupal`) for their project repos, and come up with something else for the actual source repo. No one is just calling it `project`, and we certainly didn't want to make it super verbose like `yii2-app-basic` or `symfony/framework-standard-edition`.

I do agree that it can be confusing at first – I was initially confused by Laravel’s setup too – but no one is going to type the project name for the first time without learning what to type from the documentation, so I’m not sure it’s a serious issue. Plus we do explain the difference between the repos right at the top of our [installation instructions](https://github.com/craftcms/docs/blob/v3/en/installation.md#0-introduction).

**Comment by ostark** [comment]
I find Laravel is confusing as well ;-)

Symfony changed from symfony/framework-standard-edition to symfony/skeleton with the SF4 release.

**Comment by jasonmccallister** [comment]
I think this works the way it is but could see the confusion.. TBH as a Laravel user, I have the CLI installed and struggle to remember what the “upstream” is... so maybe this goes both ways?
