### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by hybridinteractive** [craftcms/craft#19]
Running the latest 3.0.0-RC16.1

Originally I had another site' license implemented on a new site. I then wiped it out to get rid of the persistent warning. Since then my client purchased the license on staging. But now I'm getting `You’re running Craft Pro with a Craft Personal license. Resolve`. Upon clicking resolve the license warning goes away only to keep coming back at random times. I click Resolve then it show Pro has been purchased and Installed.

![screen shot 2018-03-26 at 10 17 54 am](https://user-images.githubusercontent.com/5711553/37918665-fcbb36c2-30de-11e8-8bed-989bf3281798.png)
![screen shot 2018-03-26 at 10 18 01 am](https://user-images.githubusercontent.com/5711553/37918669-ff9f9194-30de-11e8-8ea2-1093b4f1badf.png)

What can be done to resolve this?

**Comment by angrybrad** [comment]
This sounds suspiciously like a but that should have been fixed in the 16.1 release.  Can you try clearing your `craft/storage/runtime/cache` folder and see if that helps?  Craft caches license info for 24 hours at a time.

**Comment by hybridinteractive** [comment]
I cleared all of the caches via the dashboard, is that what you mean? Or should I just remove that folder altogether?

**Comment by angrybrad** [comment]
Either one should work.  If you're still getting that error after doing those, can you shoot an email to support@craftcms.com with some CP/(s)FTP creds for the site so we can poke around a bit?
