### ISSUE TITLE
400 error on sending the support form

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/craft#2]
I get a 400 BadRequestHttpException error on submitting the support form:

![schermafbeelding 2017-01-31 om 21 31 19](https://cloud.githubusercontent.com/assets/6794819/22483255/baf5cac6-e7fc-11e6-90e5-23ee645c82f8.png)

**Comment by brandonkelly** [comment]
Please post on the https://github.com/craftcms/cms repo
