### ISSUE TITLE
Wording of comment in general.php is misleading (omitScriptNameInUrls)

### ISSUE THREAD

**Issue by craftedsystems** [craftcms/craft#21]
The comment in `general.php` is misleading.

https://github.com/craftcms/craft/blob/7460a38cabb75ab949a1f03b15f0ab72cb82f00d/config/general.php#L20

Setting true does not show `index.php`, but hide it.
Please change to this, like used in the source code:
> //  Whether generated URLs should omit "index.php"

**Comment by brandonkelly** [comment]
Good point. Done!
