### ISSUE TITLE
Security Key isn’t optional

### ISSUE THREAD

**Issue by carlcs** [craftcms/craft#23]
It would be nice if there was a note in the .env and config/general.php files that setting a security isn’t optional.

**Comment by brandonkelly** [comment]
There’s [this](https://docs.craftcms.com/v3/installation.html#step-3-set-a-security-key) in the installation instructions:

> ** Step 3: Set a Security Key**
> 
> Each Craft project should have a unique security key, which is shared between each of the environments that the project in installed on.
>  …

Everything in the `.env` file is required, except `DB_PORT` which already indicates that it’s optional by saying what value it will default to, so it might make things more confusing if all of a sudden just one of the values says that it’s required – unless we explicitly say that all of  them are required, but that seems overkill.

**Comment by carlcs** [comment]
Ah, I was too late. :) I've been meaning to open this issue some days ago, before you added the sentence to the Install docs.
