### ISSUE TITLE
Database driver is not a environment specific config

### ISSUE THREAD

**Issue by carlcs** [craftcms/craft#25]
Unless I’m missing something it’s not really practicable to use 'mysql' in one environment and 'pgsql' in another.

https://github.com/craftcms/craft/blob/f5c0828fa06065bff8c5c9212d9a81fc7606bed6/config/db.php#L12

**Comment by brandonkelly** [comment]
The installer’s ability to define database connection settings (including the driver) only works if `config/db.php` is getting all its values from environment variables defined in `.env` (using the same variable names that this project uses).

Once connection settings are established, you’re correct that there’s not much value in defining the DB driver in `.env` versus just hard-coding it in `config/db.php`.
