### ISSUE TITLE
HTTP 503 – ServiceUnavailableHttpException

### ISSUE THREAD

**Issue by martynbiz** [craftcms/craft#30]
I'm trying to install CraftCMS (with composer create-project method) for the first time, and appear to have gone through all the steps on the installation guide - https://docs.craftcms.com/v3/installation.html#step-1-download-craft - yet I'm getting an Exception.

`HTTP 503 – Service Unavailable – craft\web\ServiceUnavailableHttpException`

Here is the line (509 in /var/www/craft/vendor/craftcms/cms/src/web/Application.php) that's throwing the exception:

```
// Should they be accessing the installer?
if (!$isInstalled) {
    if (!$isCpRequest) {
        throw new ServiceUnavailableHttpException();
    }
```

Below is the call stack:

```
craft\web\ServiceUnavailableHttpException in /var/www/craft/vendor/craftcms/cms/src/web/Application.php:509
Stack trace:
#0 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(184): craft\web\Application->_processInstallRequest(Object(craft\web\Request))
#1 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#2 /var/www/craft/web/index.php(21): yii\base\Application->run()
#3 {main}
```

I'm using v3.0.24 as far as I can see:

`- Installing craftcms/cms (3.0.24): Downloading (100%)`

As I haven't even got started with the CMS, I don't really know what more info to give - or where to go from here. The .env file has been copied, there really is no more instruction to do anything. Any ideas?

**Comment by angrybrad** [comment]
Sounds like Craft hasn't been installed yet?  What happens if you go to `http://yoursite.com/index.php?p=admin/install` (swapping out `yoursite.com` with your actual hostname)?

**Comment by jasonmccallister** [comment]
I get the exact same thing when it’s not installed... maybe a good idea to handle a simple “welcome” page instead? Something that returns a 20x code - specifically for load balancers/health checks?

**Comment by brandonkelly** [comment]
A 503 error seems like exactly the right response when Craft isn’t installed yet. A 20x code would give the impression that things are behaving normally, and give CDNs the idea that they should start caching the results, etc.

**Comment by gweinfurther** [comment]
I am having the same problem. I am running locally on my Windows machine and have installed Craft using Composer. When I point my browser to http://localhost/craft/index.php?p=admin/install, I get the configuration page. I fill it out, and when I submit, I get the 503 error at line 629.  

Does it make any difference that I put craft in a folder alias on my local web server (i.e., I browse to localhost/craft instead of just localhost)?
