### ISSUE TITLE
Add config-backups to storage .gitignore

### ISSUE THREAD

**Issue by timeverts** [craftcms/craft#35]
Now Craft 3.1 is out, please add the `config-backups` folder to the `.gitignore` file in the `storage` directory.

**Comment by brandonkelly** [comment]
Thanks for the reminder!

That won’t help any existing Craft 3 installs though, so as of Craft 3.1.2 it will start creating a `.gitignore` file right in the `storage/config-backups/` folder, telling Git to ignore every other file in there (similar to the one in `storage/runtime/`).
