### ISSUE TITLE
Can't run craft command with modules enabled

### ISSUE THREAD

**Issue by u-michiel** [craftcms/craft#36]
Related to issue #9 

Craft version: 3.1.6.1

When you have one or more modules defined in `config/app.php`, the `./craft` command throws an error:

```
Exception 'yii\base\InvalidArgumentException' with message 'Invalid path alias: @modules/controllers'

in .../vendor/yiisoft/yii2/BaseYii.php:154
```

It doesn't matter if the module has logic or not.
It's reproducable by just following the instructions to create a module.

https://docs.craftcms.com/v3/extend/module-guide.html#update-the-application-config

**Comment by brandonkelly** [comment]
Sounds like we just need to add that `Craft::setAlias('@modules', __DIR__);` line to the boilerplate example in the docs, yeah?

**Comment by u-michiel** [comment]
If that is the solution yes :)!

**Comment by bmcwilliams** [comment]
how do we get the command line working again when this happens?

**Comment by brandonkelly** [comment]
@bmcwilliams add the `Craft::setAlias(...)` line to your module’s `init()` method, as shown [here](https://docs.craftcms.com/v3/extend/module-guide.html#the-module-class). (The alias name must be identical to your module’s namespace.) That should fix console requests for you.
