### ISSUE TITLE
Use alias for site url based on root url defined as env var?

### ISSUE THREAD

**Issue by thomasgoemaere** [craftcms/craft#39]
Hi,

I was wondering if the following setup is a good practice.

In my .env file I defined a single rootUrl var which contains the site root url like this:

`ROOT_URL="https://www.mydomain.test"`

In the general.php config file i've created an alias (@rootUrl) that contains the ROOT_URL env var value:

`    'aliases' => [
        '@rootUrl' => getenv('ROOT_URL'),
    ],`

Then I define my craft sites as following (multilingual site), each site BASE URL is constructed with the rootUrl and a language:

![Schermafbeelding 2019-03-22 om 08 39 32](https://user-images.githubusercontent.com/1284055/54807616-185f4d80-4c7e-11e9-9c3c-45d8954ed3f3.png)

Advantages

- You don't have to define every site (language) in the code, languages are managed through the cms (in case of multisite setup, you should define a ROOT_URL for every site).
- the @rootUrl alias can be used as part of the resource path in the templates.

Disadvantages

- Could this also resolve in a caching issue ([like the @web alias](https://twitter.com/nystudio107/status/1074429502615379968))?
- ...

Does this logic makes sense or is it generally a bad idea to use aliases for the site BASE URL setting?

Thanks in advance,
Thomas

**Comment by brandonkelly** [comment]
Yep that’s definitely a good approach!
