### ISSUE TITLE
Best practices for `license.key` in terms of `.gitignore`?

### ISSUE THREAD

**Issue by khalwat** [craftcms/craft#42]
According to [More Information than You Require About Craft License Keys](https://craftcms.com/guides/more-information-than-you-require-about-craft-license-keys):

> Don’t give anyone access to the license.key file that you don’t trust or owe money to! Remember that everyone that has access to the license key can easily transfer it to a new domain.

That being the case, what's the best practices in terms of checking `license.key` into your git repository?

Obviously public would be a bad idea, but private seems on par with checking in your passwords or access tokens?

The `.gitignore` [file for this starter repo](https://github.com/craftcms/craft/blob/master/.gitignore) doesn't specifically exclude `license.key` so I figured I'd ask...

**Comment by brandonkelly** [comment]
Most Craft projects aren’t published to public repos, so generally not a major concern. And we need to update that article a bit – now with Craft ID, if you’ve claimed a Craft license there you don’t have anything to worry about, even if the license key becomes public.

**Comment by khalwat** [comment]
^ that's what I was assuming @brandonkelly -- thanks for the clarification!

**Comment by mandrasch** [comment]
Came across this trying out Craft4, wanted to publish some example repositories publicly on Github as well for DDEV + Gitpod. 

Is there a recent guide on how to approach this? Move license key to `.env` or just gitignore it? 

Couldn't find infos in this [KB: Licensing & Editions Articles](https://craftcms.com/knowledge-base/licensing-editions).

> Don’t give anyone access to the license.key file that you don’t trust or owe money to! Remember that everyone that has access to the license key can easily transfer it to a new domain.
https://craftcms.com/knowledge-base/more-information-than-you-require-about-craft-license-keys

Thanks in advance!
