### ISSUE TITLE
Template not found: dashboard

### ISSUE THREAD

**Issue by ignace** [craftcms/craft#43]
Hello,

I followed all instructions on the documentation to install craft. 

Everything worked until I do: ./craft serve/index and then go to the specified URL. I get "Template not found: dashboard"

The templates directory only has an index.html file in it. Is this the problem?

Any ideas?

**Comment by brandonkelly** [comment]
Which URL did you go to?

**Comment by lukeholder** [comment]
Please send an email to support@craftcms.com is this is still an issue for you. Thanks.
