### ISSUE TITLE
Installation error on 1.0.43.2

### ISSUE THREAD

**Issue by taylordaughtry** [craftcms/craft#49]
Running `composer create-project craftcms/craft [directory]` currently throws a `DbConnectException`.

`setup/welcome` is trying to access the DB, which of course wouldn't be available yet. [Here's](https://gist.github.com/taylordaughtry/6d54b70667c8a7eff7ef45a665137b82) the full error + stack trace, after composer finishes autoload generation. 

Package Version: `1.0.43.2`
OS X 10.13.6

**Comment by brandonkelly** [comment]
This was also reported at craftcms/cms#5083, and was fixed in Craft 3.3.9.
