### ISSUE TITLE
How fix this

### ISSUE THREAD

**Issue by Sceko** [craftcms/craft#50]
After open some in admin area

Invalid Configuration – yii\base\InvalidConfigException
Unsupported DB driver value:

**Comment by brandonkelly** [comment]
That means that this setting is not getting set properly:

https://github.com/craftcms/craft/blob/a2a9f2f047709ab41033e6388b98a8b6f15768f4/config/db.php#L12

By default it should be getting set from a `DB_DRIVER` environment variable, which the default project sets via the `.env` file:

https://github.com/craftcms/craft/blob/a2a9f2f047709ab41033e6388b98a8b6f15768f4/.env.example#L7-L8

Make sure that you actually have a `.env` file, and that it is defining the `DB_DRIVER` variable correctly. (If you are on a Mac, you can get Finder to show hidden files like `.env` by pressing <kbd>Command</kbd> <kbd>Shift</kbd> <kbd>.</kbd>.) If the file doesn’t exist, duplicate the `.env.example` file as `.env`.

**Comment by Sceko** [comment]
Thanks for answer Craft is really amazing
