### ISSUE TITLE
install-bg.png image 404 on fresh install

### ISSUE THREAD

**Issue by TheFunkyMonk** [craftcms/craft#54]
### Description

On a fresh install of Craft, I'm getting a 404 error trying to load `install-bg-1920.png` on the default index page. I see a file `installer-bg.png` in my cpresources directory, so perhaps just a file name didn't get updated from "install" to "installer"?

### Steps to reproduce

1. Install Craft via Composer using the instructions in the Craft 3 documentation
2. Load index page in a browser.

### Additional info

- Craft version: 3.4.8
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.26
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Sorry, I assumed you were referring to the installer’s background image, but you were talking about the welcome template you get when accessing the front-end by default. Just fixed that for future installs. That template is just a placeholder, but if you really want to patch your own install, you can replace your current `templates/index.html` file with this one: https://raw.githubusercontent.com/craftcms/craft/029f46db41fb8896d475649af163145d8fa1d94d/templates/index.html
