### ISSUE TITLE
What are the Craft 3.5 craft/config/project gitignore recommendations? 

### ISSUE THREAD

**Issue by jonasarts** [craftcms/craft#60]
On upgrading from Craft 3.4 to 3.5 I've got many folders and yaml's (alongside the craft/config/project/project.yaml).
Can they be put to .gitignore or what are the recommendations for updating .gitignore on upgrade?
(F.ex. I manually upgraded the craft/storage .gitignore file on the 3.5 upgrade.)

**Comment by jonasarts** [comment]
And how do I remove the "bug" label here? (Sorry for that.)

**Comment by ostark** [comment]
Project Config files are expected to be under version control. @jonasarts

**Comment by lukeholder** [comment]
Answer to these questions is in the docs here: https://craftcms.com/docs/3.x/project-config.html#what-s-stored-in-project-config
